HW4 is completed
axp-dev/otus-golang pull request #4
Opened 2020-12-27 14:06 UTC by axp-dev

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-01-07 14:21 UTC, balabanovds requested changes
Спасибо! Хорошая работа.

Осталось написать тест на логику выталкивания редкоиспользуемых элементов.
Пока оценка 7/10

Успехов!

https://otus.ru/teacher-lk/homework/149037/9018/

2021-01-07 14:21 UTC, balabanovds approved these changes

2021-01-08 21:54 UTC, axp-dev commented on hw04_lru_cache/list.go
> +	if i.Prev == nil || l.len == 1 {
> Осталось написать тест на логику выталкивания редкоиспользуемых элементов.

Разве в здесь нет это логики? [cache_test.go](https://github.com/axp-dev/otus-golang/blob/d54ecc118a52dfcfb7834a11d76c2fdb9ed1f27c/hw04_lru_cache/cache_test.go#L52)

2021-01-09 08:26 UTC, balabanovds commented on hw04_lru_cache/list.go
> +	if i.Prev == nil || l.len == 1 {
Если я правильно понял то до [строчки](https://github.com/axp-dev/otus-golang/blob/d54ecc118a52dfcfb7834a11d76c2fdb9ed1f27c/hw04_lru_cache/cache_test.go#L62) идет тест на логику выталкивания элементов из-за размера очереди, а после уже на выталкивание редкоиспользуемых элементов
Объединять два теста в один - может вызвать путаницу.. 

На Set есть проверка, при Get элемент тоже должен переноситься в начало списка. На нее проверки не увидел.
```go
c.Set("i1", 1)
val, ok = c.Get("i3")
require.False(t, ok)
require.Nil(t, val)
```

2021-01-09 11:05 UTC, merged